### ISSUE TITLE
Update to use PowerWorld's "Concise Variable Names" instead of "Variable Name"

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#1]
It turns out that despite being listed first in the PowerWorld export, the "Variable Name" column contains old/deprecated variable names, and the "Concise Variable Name" column represents the new/preferred variable names.

This definitely isn't critical, but it's probably better to fix this earlier rather than later. This will impact tests, examples, etc.

We should also consider if we want to support both variable names.

Finally, this will require documentation updates (which should be made no matter what to make it clear to our users what we support).

**Comment by mzy2240** [comment]
This is a very good find. What do you mean that the "variable name" column contains old/deprecated names? How did you find that? And is there a way to generate a list of valid "concise variable names" or any resource that points to the preferred variable names?

**Comment by blthayer** [comment]
When you export the variable names like so:

![export_screen_shot](https://user-images.githubusercontent.com/14652512/69274033-1f3cb800-0b9f-11ea-9a9b-7d34015bbf09.png)

you'll get an Excel sheet that looks like:
![excel_screen_shot](https://user-images.githubusercontent.com/14652512/69274132-5a3eeb80-0b9f-11ea-89cd-5bfb5a742741.PNG)

It turns out that the "Concise Variable Name" is preferred, while "Variable Name" is legacy. I learned this in the PowerWorld course. So, we should switch to those, and ensure it's well documented/clear to our users that that's what we support.

**Comment by mzy2240** [comment]
Currently when `pw_order = True`, ESA will use exactly the same variable names as shown in the model explorer. The tradeoff is, you will need to do type conversion by urself (which is very trivial). People who prefer using the same variable names could use this feature.

**Comment by mzy2240** [comment]
Close the issue for now.
