### ISSUE TITLE
Initialization for SolvePowerFlow()

### ISSUE THREAD

**Issue by SaeedNsh** [mzy2240/ESA#113]
Dear Author,

Is there any option for changing the initialization of the solver's method in terms of the maximum number of iterations or other parameters? I need to decrease the maximum number of iterations or adjust the threshold.

Sincerely

**Comment by mzy2240** [comment]
You can change the parameter with exactly the same procedure as changing LoadMW. The object name is "Sim_Solution_Options" and the field name is "MaxItr". Set `pw_order = True` if you received an `Object not found` warning.
