### ISSUE TITLE
Implement and test TSGetContingencyResults method

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#22]

**Comment by blthayer** [comment]
This one shouldn't be included. My mistake.

**Comment by mzy2240** [comment]
Actually it is a simauto function. Can you implement that one?

**Comment by blthayer** [comment]
You're correct. I'm on it.

**Comment by blthayer** [comment]
@mzy2240 @SmartJingJing123 - I'm going to reassign this one to the two of you. Can you please:

- Review the docstring and make sure it makes sense. Revise as necessary
- Review the tests
- Add more tests (optional, but I think it could be useful to add tests that call the method in different ways)
