### ISSUE TITLE
Bump version to 1.0.0 as last step for JOSS paper

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#27]

**Comment by blthayer** [comment]
@mzy2240 - since we've implemented all the functions, you're welcome to release version 1.0.0 whenever you'd like. All that we have left are documentation changes (none of which are major enough to prevent us releasing, in my opinion). We're not in a hurry to release, however.

**Comment by mzy2240** [comment]
Released the 1.0.0 version to PYPI.
