### ISSUE TITLE
Create function for setting SimAuto flags/constants

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#3]
There are some SimAuto constants/flags such as "CreateIfNotFound" that users may want to set. We should create a single entry point for setting these.

**Comment by mzy2240** [comment]
Fixed in b89ac5a5f0bbe5bc866542e48ce761d06cbc7a67.

**Comment by mzy2240** [comment]
Other properties like CurrentDir, ProcessID, RequestBuildDate and ExcelApp might be implemented based on requests. Close the issue now and feel free to re-open it if it does not solve your problem.

**Comment by blthayer** [comment]
@mzy2240 - I think we should create a function so that you can change these on the fly, rather than once upon initialization.
