### ISSUE TITLE
Draft statement of need

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#31]
Discuss why one would use an automation tool like ESA instead of directly using PowerWorld on its own.

**Comment by mzy2240** [comment]
- Getting data from a power system model for other application, like graph analysis or signal processing
- Automate some parameter search process, like dynamic model tunning
- Provide a bridge between the power system simulation and the machine learning application

You guys are welcomed to provide more reasons @SmartJingJing123 @blthayer

**Comment by blthayer** [comment]
I like these. I think some other ideas might be:
- Co-simulation with other domains such as transportation, communication, or natural gas
- General task automation

**Comment by blthayer** [comment]
Update the why use ESA documentation to include this stuff

**Comment by mzy2240** [comment]
Updated in #7ae001e.
