### ISSUE TITLE
Contact PowerWorld, request ESA be listed on their website

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#35]
To maximize our visibility, we should see if we can get PowerWorld to link to ESA in their documentation and on their website. We can do this as one of the last tasks related to the JOSS submission.

**Comment by blthayer** [comment]
@mzy2240 - can you either email me Caroline's email address or email her related to this? We might want to wait until after we've merged develop into master, bumped the version to 1.0, and added the latest on PyPi.

**Comment by mzy2240** [comment]
I will email her shortly. I will also share her email to you via email.

**Comment by mzy2240** [comment]
Just emailed. Will close the issue once a response is received.

**Comment by blthayer** [comment]
PowerWorld, for whatever reason, doesn't want to list our tool. Closing.
