### ISSUE TITLE
Update RELEASE_PROCESS.rst file

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#37]
Please fill in this file with details on the release process. I've started it.

**Comment by mzy2240** [comment]
@blthayer Please check the new RELEASE_PROCESS.rst and let me know if you prefer adding more details. If you think it is good, please close this issue.

**Comment by blthayer** [comment]
@mzy2240 - thank you! I just made some small adjustments. Would it be easy to add the commands needed for the step `Generate the distribution archive`?

**Comment by mzy2240** [comment]
> @mzy2240 - thank you! I just made some small adjustments. Would it be easy to add the commands needed for the step `Generate the distribution archive`?

Now it should look better : )

**Comment by blthayer** [comment]
@mzy2240 - looks great! Thank you!
