### ISSUE TITLE
Incorporate testing coverage into documentation

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#38]
https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html#sphinx.ext.coverage.coveragebuilder

**Comment by blthayer** [comment]
@mzy2240 - this is complete. Please run `docs/rst/coverage_to_rst.py` after installing `coverage` and `tabulate` packages.

**Comment by mzy2240** [comment]
@blthayer 
![image](https://user-images.githubusercontent.com/18620336/78412691-e0515100-75d9-11ea-8676-6ca3587c2c45.png)
Is the output expected?

**Comment by blthayer** [comment]
@mzy2240 - no, that's not expected. I'll try running with Python 3.8 and see if I get the same warning.

**Comment by blthayer** [comment]
@mzy2240 - I was running from PyCharm, which does some automatic path patching. I've fixed it now, please try again.

This underscores the importance of running everything from the terminal during a release - we don't want the magic of PyCharm to hide things that are broken.

**Comment by SmartJingJing123** [comment]
@blthayer I have some doubt after running the script. I got a result of Percentage Coverage = 100 in the README.rst, but there are some errors in the output, is this expected? Screenshot of the errors is attached:
![image](https://user-images.githubusercontent.com/47085972/78454204-47afe500-765c-11ea-86d9-f4b7bf44d980.png)

**Comment by blthayer** [comment]
@SmartJingJing123 - at the very beginning of the output, there's some text that says:

```
************************************************************************************************************************
RUNNING TESTS
Ignore any exceptions until you see a bunch of "*" characters.
```

The errors you see are intentionally raised during the tests - essentially testing that error handling is working appropriately. I went ahead and updated the printing in the script so that it's more clear that those printed errors are expected behavior. You can see my changes in the following commit: 7bcb2d3f839d4489a8edaed59389f4c5e5c30f60
