### ISSUE TITLE
Documentation-only release

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#49]
I've updated the text around our citations to encourage people to check back later for an up-to-date citation. As such, I'd like to update the documentation both on GitHub and out on PyPi.

@mzy2240 - would you be willing to create a new release? No change to version number, no need to run the tests, etc. All we need is rebuilt documentation and an update on PyPi (so the top-level README gets updated).

**Comment by blthayer** [comment]
Here's the changes I made: e4c0f26811eece34261f4d2c8385a1d6a144a88c

**Comment by mzy2240** [comment]
This issue is solved in https://github.com/mzy2240/ESA/commit/267ae31eef744cb63c446aea36e806088f7d6c89
