### ISSUE TITLE
Publicize and/or advertise ESA

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#50]
After we have an official publication listed as our citation, we should start advertising ESA. One example might include making a "Powerglobe" announcement.

**Comment by blthayer** [comment]
@mzy2240, @SmartJingJing123 - I'll be emailing folks at PNNL about ESA now that it's "complete" and we've got the JOSS paper out. Would you guys be willing to take point on advertising it elsewhere?

**Comment by SmartJingJing123** [comment]
https://github.com/mzy2240/ESA/issues/50#issuecomment-645636114
I could volunteer to advertise on Linkedin.

**Comment by mzy2240** [comment]
Yeah I will advertise it to my intern company as well as friends in our field.

**Comment by blthayer** [comment]
@mzy2240 @SmartJingJing123 - I've informed my PNNL network about ESA, and also updated the group regarding the JOSS publication. I propose we close this for now, and if anyone has more ideas for getting the word out, we can reopen.

**Comment by blthayer** [comment]
@mzy2240 @SmartJingJing123 

We saw some decent cloning traffic before the JOSS paper came out as well as on the day the paper was published:

![Screenshot from 2020-06-24 08-57-15](https://user-images.githubusercontent.com/14652512/85589875-ca5f9500-b5f8-11ea-855d-0f03ed4040b6.png)
