### ISSUE TITLE
Update build date/ version methodology

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#55]
@mzy2240 - would you have time to tackle this today? I gained some information from PowerWorld this morning:

> There's a way to get both the version number, and the build date in a date format: GetParametersSingleElement( "PowerWorldSession", ["Version", "ExeBuildDate"], ["", ""])

We could run this in __init__ and simply add a `version` attribute to `SAW`. Then, we wouldn't have to mess around with any of the writing to file stuff.

**Comment by mzy2240** [comment]
Ok
