### ISSUE TITLE
Update all citation locations with the new JOSS citation after published

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#67]

**Comment by mzy2240** [comment]
Just modified my N-X paper with the latest citation.
@SmartJingJing123 Can you check whether the ref in the RIDES-related papers need to update also?

**Comment by blthayer** [comment]
@mzy2240 - I'm going to close this since I've updated the citation in the main README as well as in the .rst file. I'll go ahead and email the group with the new citation.

**Comment by SmartJingJing123** [comment]
> Just modified my N-X paper with the latest citation.
> @SmartJingJing123 Can you check whether the ref in the RIDES-related papers need to update also?

Yes, I will add ESA in the evaluation metric paper since I used it in the TSR file decoding process. And I could think about whether ESA can be added in the RIDES development paper as well.
