### ISSUE TITLE
Stop supporting python 3.5/3.6 and add support for 3.10

### ISSUE THREAD

**Issue by mzy2240** [mzy2240/ESA#74]
Since 3.5 and 3.6 are already [EOL](https://endoflife.date/python), many packages (like numpy and numba) already stopped publishing new patches for them. We should also consider supporting python 3.10. What do you think? @blthayer

**Comment by blthayer** [comment]
I think that's a great idea! In my opinion it's unreasonable for package maintainers (like yourself) to maintain compatibility with Python versions that are no longer supported by Python.

**Comment by mzy2240** [comment]
Thanks for the suggestions!

**Comment by mzy2240** [comment]
Still need to fix the python 3.10 support issue due to the aot compiled module
