### ISSUE TITLE
Test with Pandas 1.0.*

### ISSUE THREAD

**Issue by blthayer** [mzy2240/ESA#9]
Pandas recently updated to version 1.0. There are some backwards incompatible changes. We should run tests with both >=0.24 and 1.0.

@mzy2240 - would you have time for this? If not, it's not urgent, and I could do it sometime in the upcoming weeks.

**Comment by mzy2240** [comment]
I will take a look next week. We are preparing the short course recently so really busy.

**Comment by mzy2240** [comment]
Tested in Python 3.8 with Pandas 1.0.1. Passed all the tests.
